# Generated by Django 5.1.2 on 2024-10-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_hotel_city_en_hotel_city_ru_hotel_country_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='address_ru',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
